import { Component } from '@angular/core';
import { HomeBtn } from './home-btn/home-btn';

let playing: boolean = false;
let audio: HTMLAudioElement;
const facts = [
  "Octopusse haben drei Herzen.",
  "Ein Tag auf der Venus dauert länger als ein Jahr dort.",
  "Haie existieren länger als Bäume.",
  "Der Mond entfernt sich jedes Jahr etwa 3,8 cm von der Erde.",
  "Wombats produzieren würfelförmigen Kot.",
  "Honig verdirbt praktisch nie.",
  "Ein Blitz ist heißer als die Oberfläche der Sonne.",
  "Es gibt mehr mögliche Schachpartien als Atome im Universum.",
  "Die ISS ist eines der teuersten Bauwerke der Menschheit.",
  "Pinguine können über 500 Meter tief tauchen.",
  "Katzen haben über 100 verschiedene Lautäußerungen.",
  "Hunde besitzen etwa 300 Millionen Geruchsrezeptoren.",
  "Der Pazifik ist größer als alle Kontinente zusammen.",
  "Bambus kann über 90 cm pro Tag wachsen.",
  "Kolibris können rückwärts fliegen.",
  "Ein Blauwalherz kann über 180 kg wiegen.",
  "Der Mensch blinzelt etwa 20.000 Mal pro Tag.",
  "Die Erde ist etwa 4,5 Milliarden Jahre alt.",
  "Die Sonne enthält über 99 % der Masse des Sonnensystems.",
  "Saturn könnte theoretisch auf Wasser schwimmen.",
  "Der höchste Wasserfall der Welt ist Angel Falls.",
  "Der größte Vulkan ist Olympus Mons auf dem Mars.",
  "Ein Regentropfen fällt etwa mit 30 km/h.",
  "Der menschliche Körper besteht zu etwa 60 % aus Wasser.",
  "Einige Quallen sind biologisch fast unsterblich.",
  "Der Marianengraben ist über 11 km tief.",
  "Der schnellste Vogel ist der Wanderfalke.",
  "Es gibt über 20.000 bekannte Bienenarten.",
  "Der größte Fisch ist der Walhai.",
  "Einige Frösche können einfrieren und überleben.",
  "Die längste Gebirgskette liegt unter Wasser.",
  "Der Jupiter hat über 90 bekannte Monde.",
  "Einige Pilze können im Dunkeln leuchten.",
  "Ein menschliches Herz schlägt etwa 100.000 Mal täglich.",
  "Ein Blitz schlägt etwa 100 Mal pro Sekunde auf der Erde ein.",
  "Einige Ameisen betreiben Landwirtschaft.",
  "Es gibt mehr Bäume auf der Erde als Sterne in der Milchstraße.",
  "Der menschliche Körper hat etwa 37 Billionen Zellen.",
  "Einige Eidechsen können ihren Schwanz abwerfen.",
  "Die Antarktis ist die größte Wüste der Erde.",
  "Der größte Dinosaurier war wahrscheinlich Argentinosaurus.",
  "Ein Elefant kann über 10 Liter Wasser im Rüssel tragen.",
  "Die Erdrotation verlangsamt sich minimal jedes Jahr.",
  "Ein Schneeflocke hat oft sechs Arme.",
  "Die meisten Meteoriten stammen aus dem Asteroidengürtel.",
  "Der Mount Everest wächst jedes Jahr minimal.",
  "Der menschliche Körper enthält etwa 206 Knochen.",
  "Einige Fische können ihr Geschlecht wechseln.",
  "Einige Pflanzen können Fleisch verdauen.",
  "Der längste Knochen im Körper ist der Oberschenkelknochen.",
  "Der Amazonas führt mehr Wasser als jeder andere Fluss.",
  "Einige Tiere sehen ultraviolettes Licht.",
  "Der Mars hat die größten Staubstürme im Sonnensystem.",
  "Einige Bäume können über 5000 Jahre alt werden.",
  "Korallenriffe sind vom Weltraum sichtbar.",
  "Der größte bekannte Stern ist UY Scuti.",
  "Einige Pilze können Plastik abbauen.",
  "Der größte bekannte Eisberg war größer als Jamaika.",
  "Der menschliche Körper verliert täglich Millionen Hautzellen.",
  "Einige Tiere nutzen Magnetfelder zur Navigation.",
  "Einige Bakterien überleben extreme Strahlung.",
  "Der größte Regenwald ist der Amazonas.",
  "Die Sahara war früher eine grüne Landschaft.",
  "Ein Kolibri schlägt seine Flügel bis zu 80 Mal pro Sekunde.",
  "Die Erde dreht sich am Äquator mit etwa 1670 km/h.",
  "Ein Blitz kann bis zu 30.000 Grad heiß werden.",
  "Einige Vögel können im Schlaf fliegen.",
  "Ein Wal kann über 30 Meter lang werden.",
  "Der längste Fluss ist entweder Nil oder Amazonas.",
  "Ein Oktopus hat blaues Blut.",
  "Einige Spinnen können über Wasser laufen.",
  "Der Mensch produziert täglich etwa einen Liter Speichel.",
  "Einige Tiere können ganze Gliedmaßen regenerieren.",
  "Der größte Käfer ist der Goliathkäfer.",
  "Der Jupiter ist so groß, dass über 1300 Erden hinein passen.",
  "Die Milchstraße enthält hunderte Milliarden Sterne.",
  "Der größte Kontinent ist Asien.",
  "Der tiefste See ist der Baikalsee.",
  "Einige Haie müssen ständig schwimmen.",
  "Die Erde ist leicht abgeflacht.",
  "Ein Jahr auf Merkur dauert 88 Tage.",
  "Ein Tag auf Merkur dauert 59 Erdtage.",
  "Einige Schildkröten werden über 150 Jahre alt.",
  "Der schnellste Fisch ist der Segelfisch.",
  "Einige Fledermäuse können über 160 km/h fliegen.",
  "Der menschliche Magen erneuert seine Schleimhaut ständig.",
  "Einige Bäume kommunizieren über Wurzeln.",
  "Der größte Planet ist Jupiter.",
  "Die Sonne ist etwa 109-mal größer als die Erde.",
  "Einige Frösche können über 20 Jahre alt werden.",
  "Der Mond verursacht Gezeiten.",
  "Ein Blitz kann mehrere Kilometer lang sein.",
  "Einige Insekten können über Wasser laufen.",
  "Der größte bekannte Krater ist über 300 km breit.",
  "Einige Tiere schlafen im Stehen.",
  "Der größte Vogel ist der Strauß.",
  "Der kleinste Vogel ist die Bienenelfe.",
  "Einige Pflanzen bewegen sich aktiv.",
  "Der Mensch hat etwa 650 Muskeln.",
  "Einige Tiere können ohne Sauerstoff überleben.",
  "Der Saturn besitzt auffällige Ringe.",
  "Einige Vulkane liegen unter Wasser.",
  "Der Pazifik enthält über die Hälfte des Ozeanwassers.",
  "Einige Tiere können Farbe wechseln.",
  "Kühe haben beste Freunde und leiden unter Stress, wenn sie getrennt werden.",
  "In der Schweiz ist es illegal, nur ein einzelnes Meerschweinchen zu halten.",
  "Ein Gramm DNA kann theoretisch bis zu 215 Petabyte an Daten speichern.",
  "Bananen sind botanisch gesehen Beeren, Erdbeeren hingegen nicht.",
  "Der Erfinder der Pringles-Dose wurde nach seinem Tod in einer solchen bestattet.",
  "Wussten Sie, dass Kleopatra zeitlich näher an der Mondlandung lebte als am Bau der Pyramiden von Gizeh?",
  "Eichhörnchen vergessen jedes Jahr tausende vergrabene Nüsse und pflanzen so Millionen Bäume.",
  "Wölfe können beim Heulen die Tonlage anpassen, um die Rudelgröße größer erscheinen zu lassen.",
  "Das Wort 'Robot' stammt vom tschechischen Wort 'robota' ab, was 'Zwangsarbeit' bedeutet.",
  "Krokodile können ihre Zunge nicht herausstrecken.",
  "Ein Goldfisch hat ein längeres Gedächtnis als drei Sekunden – es reicht Monate weit.",
  "Die Nationalhymne von Spanien hat keinen offiziellen Text.",
  "In Japan gibt es über 5 Millionen Verkaufsautomaten.",
  "Ein Blauwal kann unter Wasser Töne erzeugen, die noch in 800 km Entfernung hörbar sind.",
  "Flusspferdschweiß ist rötlich und wirkt wie ein natürlicher Sonnenschutz.",
  "Ein durchschnittlicher Wolkenhaufen wiegt etwa 500.000 Kilogramm.",
  "In Frankreich war die Guillotine noch legal, als der erste Star Wars Film in die Kinos kam.",
  "Die gesamte Weltbevölkerung würde theoretisch in die Stadt Los Angeles passen (Schulter an Schulter).",
  "Schafe können menschliche Gesichter auf Fotos wiedererkennen.",
  "Schnecken können bis zu drei Jahre lang schlafen.",
  "Der Name 'Adidas' leitet sich vom Gründer Adolf ('Adi') Dassler ab.",
  "Das längste jemals gemessene Hühnergekrächze dauerte etwa 13 Sekunden.",
  "Ratten lachen, wenn man sie kitzelt, allerdings in einem für Menschen unhörbaren Ultraschallbereich.",
  "Der Eiffelturm kann im Sommer durch die Hitzeausdehnung um bis zu 15 cm wachsen.",
  "Schotten haben über 400 verschiedene Wörter für 'Schnee'.",
  "Das Internet wiegt etwa so viel wie eine mittelgroße Erdbeere (bezogen auf die Elektronenmasse).",
  "Man kann in der Schwerelosigkeit nicht rülpsen, da sich Gase und Flüssigkeiten im Magen nicht trennen.",
  "Ein Oktopus hat neun Gehirne – eines im Kopf und eines in jedem Arm.",
  "Der älteste bekannte Hai der Welt, der Grönlandhai, kann über 400 Jahre alt werden.",
  "Kängurus können nicht rückwärts gehen.",
  "In den USA gibt es mehr Plastik-Flamingos als echte.",
  "Die Tastaturbelegung 'QWERTY' wurde entworfen, um das Schreiben zu verlangsamen, damit mechanische Schreibmaschinen nicht verhaken.",
  "Venedig steht auf Millionen von Holzpfählen, die im Schlamm nicht verrotten, weil kein Sauerstoff hinkommt.",
  "Faultiere brauchen bis zu zwei Wochen, um eine einzige Mahlzeit zu verdauen.",
  "Die Farbe Orange wurde nach der Frucht benannt, nicht umgekehrt.",
  "Der Mount Everest ist nicht der Punkt auf der Erde, der dem Weltraum am nächsten ist (das ist der Chimborazo).",
  "Bienen können Gesichter unterscheiden.",
  "In Finnland gibt es mehr Saunen als Autos.",
  "Das Herz einer Garnele befindet sich in ihrem Kopf.",
  "Eisbären haben schwarze Haut unter ihrem weißen (eigentlich transparenten) Fell.",
  "Ein Blitzschlag ist etwa 5-mal heißer als die Sonnenoberfläche.",
  "In Deutschland gibt es ein Museum, das ausschließlich dem Currywurst-Kult gewidmet war.",
  "Seepferdchen sind die einzigen Tiere, bei denen die Männchen die Jungen austragen.",
  "Der erste Computerbug war eine echte Motte, die in einem Relais feststeckte.",
  "Man kann theoretisch aus Erdnussbutter Diamanten herstellen.",
  "Der Tyrannosaurus Rex lebte zeitlich näher am iPhone als am Stegosaurus.",
  "Nutella hat einen Lichtschutzfaktor von etwa 9,7 (bitte nicht als Sonnencreme nutzen!).",
  "Eine einzige Kuh stößt pro Tag etwa 200 bis 500 Liter Methan aus.",
  "An Bord der Voyager-Sonden befindet sich eine goldene Schallplatte mit Geräuschen der Erde.",
  "Die Fläche Russlands ist größer als die des Zwergplaneten Pluto.",
  "Schmetterlinge schmecken mit ihren Füßen.",
  "Die Unendlichkeitstaste bei einem Taschenrechner ist oft nur eine liegende 8.",
  "In Neuseeland gibt es einen Ort mit 85 Buchstaben im Namen: Taumatawhakatangihangakoauauotamateaturipukakapikimaungahoronukupokaiwhenuakitanatahu.",
  "Es regnet auf dem Saturn und Jupiter flüssige Diamanten.",
  "Das Gehirn eines Straußes ist kleiner als seine Augen.",
  "Koalas haben fast identische Fingerabdrücke wie Menschen.",
  "Barbie-Puppen haben einen vollen Namen: Barbara Millicent Roberts.",
  "In Island gibt es keine Mücken.",
  "Ein Hai kann einen einzelnen Blutstropfen in einem olympischen Schwimmbecken riechen.",
  "Der Zauberwürfel hat über 43 Trillionen verschiedene Stellungen.",
  "Der menschliche Kiefermuskel ist einer der stärksten Muskeln im Körper.",
  "Das kälteste bewohnte Dorf der Welt ist Oimjakon in Sibirien.",
  "Ein Liter Meerwasser enthält etwa 13 Milliardstel Gramm Gold.",
  "Zitronen enthalten mehr Zucker als Erdbeeren.",
  "Pluto hat seit seiner Entdeckung bis heute noch keine einzige Runde um die Sonne vollendet.",
  "Der Erfinder des Frisbees wurde nach seinem Tod verbrannt und zu einer Frisbee-Scheibe gepresst.",
  "Das älteste noch bestehende Unternehmen der Welt ist ein Hotel in Japan (seit 705 n. Chr.).",
  "Ein neugeborener Panda ist kleiner als eine Maus.",
  "Die Zunge eines Blauwals wiegt so viel wie ein ganzer Elefant.",
  "Schweine können nicht in den Himmel schauen.",
  "In Arizona ist es gesetzlich verboten, einen Kaktus zu fällen.",
  "Esel töten jährlich mehr Menschen als Haie.",
  "Ein Bleistift kann theoretisch eine Linie von 56 km Länge ziehen.",
  "Der Mensch teilt etwa 50 % seiner DNA mit einer Banane.",
  "In North Dakota wurde noch nie ein Erdbeben registriert.",
  "Ein Kolibri wiegt weniger als eine Ein-Euro-Münze.",
  "Die einzige Zahl, die im Deutschen so viele Buchstaben wie ihren Wert hat, ist die 'Vier'.",
  "Fliegen leben nur etwa 15 bis 30 Tage.",
  "Ein neugeborenes Känguru ist nur etwa zwei Zentimeter groß.",
  "Eskimos nutzen Kühlschränke, um zu verhindern, dass ihr Essen gefriert.",
  "Lego ist der größte Reifenhersteller der Welt (nach Stückzahl).",
  "Ketchup wurde im 19. Jahrhundert als Medizin gegen Durchfall verkauft.",
  "Das erste über 1-Gbit-Netzwerk versendete Objekt war ein Bild von der Band 'Les Horribles Cernettes'.",
  "In Kentucky ist es illegal, eine Eiswaffel in der Gesäßtasche zu tragen.",
  "Flamingos werden rosa, weil sie Algen und Krebstiere mit viel Carotinoid fressen.",
  "Die Lippen des Menschen sind hunderte Male empfindlicher als die Fingerspitzen.",
  "Katzen können ihren Kiefer nicht seitwärts bewegen.",
  "Der Name 'Google' entstand durch einen Rechtschreibfehler von 'Googol'.",
  "Es gibt auf der Welt mehr Fake-Profile als echte Menschen in Deutschland.",
  "Das längste Wort im Duden ist die 'Rindfleischetikettierungsüberwachungsaufgabenübertragungsgesetz'.",
  "In der Schwerelosigkeit werden Astronauten bis zu 5 cm größer.",
  "Ein einzelner Teelöffel eines Neutronensterns würde Milliarden Tonnen wiegen.",
  "Eulen haben keine Augäpfel, sondern röhrenförmige Augen, die fest im Schädel sitzen.",
  "Der Herzschlag eines Blauwals ist aus zwei Meilen Entfernung messbar.",
  "In Schweden gibt es ein Hotel, das komplett aus Eis besteht und jedes Jahr neu gebaut wird.",
  "Ameisenbären haben keine Zähne.",
  "Die Freiheitsstatue trägt Schuhgröße 875.",
  "Einige Spinnenarten füttern ihre Jungen mit 'Spinnenmilch'.",
  "Der Pazifik wird jedes Jahr um etwa 2-3 cm schmaler, während der Atlantik wächst.",
  "Jeder Mensch hat einen einzigartigen Zungenabdruck."
]

@Component({
  selector: 'app-fun-facts',
  imports: [HomeBtn],
  templateUrl: './fun-facts.html',
  styleUrl: './fun-facts.sass',
})
export class FunFacts {
  playAudio() {
    if (!playing) {
      playing = true;
      let randomNumber: number = Math.floor(Math.random() * 204);
      audio = new Audio(`assets/audio/${randomNumber}.wav`);
      audio.onended = () => {
        playing = false;
      };
      audio.play();
    }
    else {
      playing = false;
      audio.pause();
    }
  }
}
