version: 2
updates:
  # Updates für npm-Pakete (Angular, RxJS, etc.)
  - package-ecosystem: "npm"
    directory: "/" # Ort deiner package.json
    schedule:
      interval: "weekly" # "daily", "weekly" oder "monthly"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "javascript"

  # Updates für deine GitHub Actions selbst
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "github-actions"
      
